//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webaip.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PRUEBAEntities : DbContext
    {
        public PRUEBAEntities()
            : base("name=PRUEBAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PERSONA> PERSONA { get; set; }
        public virtual DbSet<TAREA> TAREA { get; set; }
    
        public virtual int SPA_DELETEPERSONA(Nullable<int> iD_P)
        {
            var iD_PParameter = iD_P.HasValue ?
                new ObjectParameter("ID_P", iD_P) :
                new ObjectParameter("ID_P", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPA_DELETEPERSONA", iD_PParameter);
        }
    
        public virtual int SPA_DELETETAREA(Nullable<int> iD_T)
        {
            var iD_TParameter = iD_T.HasValue ?
                new ObjectParameter("ID_T", iD_T) :
                new ObjectParameter("ID_T", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPA_DELETETAREA", iD_TParameter);
        }
    
        public virtual int SPA_INSERTPERSONA(string nOMBRE, string aPELLIDO)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDOParameter = aPELLIDO != null ?
                new ObjectParameter("APELLIDO", aPELLIDO) :
                new ObjectParameter("APELLIDO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPA_INSERTPERSONA", nOMBREParameter, aPELLIDOParameter);
        }
    
        public virtual int SPA_INSERTTAREA(string dESCRIPCION, Nullable<int> iD_P)
        {
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var iD_PParameter = iD_P.HasValue ?
                new ObjectParameter("ID_P", iD_P) :
                new ObjectParameter("ID_P", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPA_INSERTTAREA", dESCRIPCIONParameter, iD_PParameter);
        }
    
        public virtual int SPA_UPDATEPERSONA(Nullable<int> iD_P, string nOMBRE, string aPELLIDO)
        {
            var iD_PParameter = iD_P.HasValue ?
                new ObjectParameter("ID_P", iD_P) :
                new ObjectParameter("ID_P", typeof(int));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDOParameter = aPELLIDO != null ?
                new ObjectParameter("APELLIDO", aPELLIDO) :
                new ObjectParameter("APELLIDO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPA_UPDATEPERSONA", iD_PParameter, nOMBREParameter, aPELLIDOParameter);
        }
    
        public virtual int SPA_UPDATETARE(Nullable<int> iD_T, string dESCRIPCION)
        {
            var iD_TParameter = iD_T.HasValue ?
                new ObjectParameter("ID_T", iD_T) :
                new ObjectParameter("ID_T", typeof(int));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPA_UPDATETARE", iD_TParameter, dESCRIPCIONParameter);
        }
    }
}
