//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webaip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAREA
    {
        public int ID_T { get; set; }
        public string DESCRIPCION { get; set; }
        public int ID_P { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
    }
}
